services:
  - type: web
    name: codeah-video-previewer
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false # Paste Neon Connection JDBC URL in Render UI
      - key: SPRING_DATASOURCE_USERNAME
        sync: false # Paste Neon Database Username in Render UI
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false # Paste Neon Database Password in Render UI
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
